import React,{useEffect,useMemo,useState} from "react";
import {Alert,Image,Linking,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from "react-native";
import * as ImagePicker from "expo-image-picker";
import {StatusBar} from "expo-status-bar";
import {loadAvatars,saveAvatars} from "./src/storage";
import {ACCESSORY_LABELS,AvatarAccessory,AvatarExpression,AvatarEyes,AvatarStyle,EYES_LABELS,EXPRESSION_LABELS,STYLE_LABELS,SnailAvatar} from "./src/types";

const BG="#070A12",PANEL="#101522",PANEL2="#151C2D",BLUE="#59B9FF",TEXT="#F4F7FB",MUTED="#8C98AE",RED="#F05B63",GREEN="#42D69B";
const SHELLS=["#3569B8","#B63A58","#2E8B75","#B97831","#6B4AA8","#232A38"];
const BODIES=["#E7B889","#D78383","#A7C1A0","#E5D27C","#B7A6D9","#B8B9BD"];
const demo:SnailAvatar={id:"demo",name:"Deine Teleschnecke",style:"klassisch",shellColor:"#3569B8",bodyColor:"#E7B889",eyeColor:"#FFFFFF",accessory:"keins",expression:"freundlich",eyes:"klassisch",createdAt:0};

function Snail({avatar,large=false}:{avatar:SnailAvatar;large?:boolean}){
 const s=large?220:92;
 const eyeW=avatar.eyes==="gross"?19:avatar.eyes==="schmal"?12:avatar.eyes==="cyber"?15:16;
 const eyeH=avatar.eyes==="schmal"?9:avatar.eyes==="cyber"?15:16;
 const mouthW=avatar.expression==="ueberrascht"?13:avatar.expression==="frech"?30:24;
 return <View style={[st.snail,{width:s,height:s*.92}]}>
  <View style={[st.shell,{width:s*.59,height:s*.59,right:s*.01,top:s*.18,backgroundColor:avatar.shellColor}]}>
   <Text style={[st.spiral,{fontSize:large?44:21}]}>◉</Text>
   {avatar.style==="steampunk"&&<Text style={[st.shellMark,{fontSize:large?22:11}]}>⚙</Text>}
   {avatar.style==="futuristisch"&&<View style={st.shellGlow}/>}
  </View>
  <View style={[st.body,{width:s*.57,height:s*.59,left:s*.12,bottom:0,backgroundColor:avatar.bodyColor}]}>
   {avatar.photoUri?<Image source={{uri:avatar.photoUri}} style={[st.face,{width:s*.35,height:s*.35}]}/>:<View style={[st.faceEmpty,{width:s*.35,height:s*.35}]}><Text style={{fontSize:large?32:16}}>🐌</Text></View>}
   <View style={[st.mouth,{width:mouthW,height:avatar.expression==="ueberrascht"?18:6,borderRadius:avatar.expression==="ueberrascht"?12:20}]}/>
   {avatar.accessory==="brille"&&<View style={st.glasses}><View style={st.glass}/><View style={st.glass}/></View>}
   {avatar.accessory==="monokel"&&<View style={st.monocle}/>}
   {avatar.accessory==="schal"&&<View style={st.scarf}/>}
   {avatar.accessory==="hut"&&<View style={st.hat}><View style={st.hatTop}/></View>}
  </View>
  <View style={[st.ant,{left:s*.17,height:s*.34}]}><View style={[st.eye,{width:eyeW,height:eyeH,borderRadius:eyeW/2,backgroundColor:avatar.eyeColor}]}/></View>
  <View style={[st.ant,{left:s*.36,height:s*.31}]}><View style={[st.eye,{width:eyeW,height:eyeH,borderRadius:eyeW/2,backgroundColor:avatar.eyeColor}]}/></View>
 </View>;
}
function Nav({label,icon,active,onPress}:{label:string;icon:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={st.navItem}><Text style={[st.navIcon,active&&{color:BLUE}]}>{icon}</Text><Text style={[st.navLabel,active&&{color:TEXT}]}>{label}</Text></Pressable>}

export default function App(){
 const [tab,setTab]=useState<"home"|"contacts"|"create"|"settings">("home");
 const [avatars,setAvatars]=useState<SnailAvatar[]>([]);
 const [editing,setEditing]=useState<SnailAvatar|null>(null);
 const [name,setName]=useState(""); const [phone,setPhone]=useState(""); const [photo,setPhoto]=useState<string|undefined>();
 const [style,setStyle]=useState<AvatarStyle>("klassisch"); const [shellColor,setShellColor]=useState("#3569B8"); const [bodyColor,setBodyColor]=useState("#E7B889");
 const [expression,setExpression]=useState<AvatarExpression>("freundlich"); const [eyes,setEyes]=useState<AvatarEyes>("klassisch"); const [accessory,setAccessory]=useState<AvatarAccessory>("keins");
 const [call,setCall]=useState<SnailAvatar|null>(null);
 useEffect(()=>{loadAvatars().then(x=>setAvatars(x.length?x:[demo]))},[]);
 const list=useMemo(()=>avatars.filter(x=>x.name.trim()),[avatars]);
 async function choose(){const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:["images"],allowsEditing:true,aspect:[1,1],quality:.9});if(!r.canceled)setPhoto(r.assets[0].uri)}
 function create(){setEditing(null);setName("");setPhone("");setPhoto(undefined);setStyle("klassisch");setShellColor("#3569B8");setBodyColor("#E7B889");setExpression("freundlich");setEyes("klassisch");setAccessory("keins");setTab("create")}
 async function save(){
  if(!name.trim()){Alert.alert("Name fehlt","Gib deiner Teleschnecke einen Namen.");return}
  const item:SnailAvatar=editing?{...editing,name:name.trim(),phone:phone.trim(),photoUri:photo,style,shellColor,bodyColor,expression,eyes,accessory}:{id:Date.now().toString(),name:name.trim(),phone:phone.trim(),photoUri:photo,style,shellColor,bodyColor,eyeColor:"#FFFFFF",accessory,expression,eyes,createdAt:Date.now()};
  const next=editing?avatars.map(x=>x.id===editing.id?item:x):[item,...avatars]; setAvatars(next); await saveAvatars(next); setEditing(null); setTab("contacts");
 }
 function edit(a:SnailAvatar){setEditing(a);setName(a.name);setPhone(a.phone||"");setPhoto(a.photoUri);setStyle(a.style);setShellColor(a.shellColor);setBodyColor(a.bodyColor);setExpression(a.expression||"freundlich");setEyes(a.eyes||"klassisch");setAccessory(a.accessory||"keins");setTab("create")}
 function dial(a:SnailAvatar){if(!a.phone){Alert.alert("Keine Telefonnummer","Füge zuerst eine Telefonnummer hinzu.");return}Linking.openURL("tel:"+a.phone).catch(()=>Alert.alert("Anruf nicht möglich","Dieses Gerät kann keinen Telefonanruf starten."))}
 async function remove(a:SnailAvatar){const next=avatars.filter(x=>x.id!==a.id);setAvatars(next);await saveAvatars(next)}
 const preview:SnailAvatar={...demo,name:name||"Deine Teleschnecke",photoUri:photo,style,shellColor,bodyColor,expression,eyes,accessory};
 if(call)return <SafeAreaView style={st.safe}><StatusBar style="light"/><View style={st.call}><Pressable onPress={()=>setCall(null)}><Text style={st.back}>‹</Text></Pressable><Text style={st.kicker}>TELESCHNECKE</Text><Text style={st.callTitle}>Anruf</Text><Snail avatar={call} large/><Text style={st.callName}>{call.name}</Text><Text style={st.muted}>Bereit für deinen Anruf</Text><View style={st.callActions}><Pressable onPress={()=>setCall(null)} style={[st.callBtn,{backgroundColor:RED}]}><Text style={st.callBtnText}>×</Text><Text style={st.callBtnLabel}>Abbrechen</Text></Pressable><Pressable onPress={()=>dial(call)} style={[st.callBtn,{backgroundColor:GREEN}]}><Text style={st.callBtnText}>☎</Text><Text style={st.callBtnLabel}>Anrufen</Text></Pressable></View><Text style={st.note}>Der echte Anruf wird über die native Telefonfunktion des Geräts gestartet.</Text></View></SafeAreaView>;

 return <SafeAreaView style={st.safe}><StatusBar style="light"/>
  <View style={st.header}><View><Text style={st.logo}>TELESCHNECKE</Text><Text style={st.tag}>Deine Kontakte. Dein Stil.</Text></View><Pressable onPress={create} style={st.add}><Text style={st.addText}>＋</Text></Pressable></View>
  {tab==="home"&&<ScrollView contentContainerStyle={st.content}><View style={st.hero}><Text style={st.kicker}>DEINE PERSÖNLICHE ANRUFWELT</Text><Text style={st.title}>Jeder Kontakt bekommt{"\n"}seine eigene <Text style={{color:BLUE}}>Teleschnecke.</Text></Text><Text style={st.copy}>Foto auswählen, Gesicht als Avatar einsetzen und anschließend Stil, Augen, Ausdruck, Haus und Zubehör selbst kombinieren.</Text><Pressable style={st.primary} onPress={create}><Text style={st.primaryText}>🐌 Teleschnecke erstellen</Text></Pressable></View><Text style={st.section}>Deine Teleschnecken</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{list.slice(0,8).map(a=><Pressable key={a.id} onPress={()=>edit(a)} style={st.card}><Snail avatar={a}/><Text style={st.cardName}>{a.name}</Text><Text style={st.muted}>{STYLE_LABELS[a.style]}</Text></Pressable>)}</ScrollView><View style={st.info}><Text style={st.infoTitle}>Original statt Kopie</Text><Text style={st.infoText}>Die App nutzt eigene Schnecken-Grundformen und frei kombinierbare Merkmale. Mitgebrachte Fotos bleiben in Version 1 lokal auf deinem Gerät.</Text></View></ScrollView>}
  {tab==="contacts"&&<ScrollView contentContainerStyle={st.content}><Text style={st.pageTitle}>Kontakte</Text>{list.map(a=><View key={a.id} style={st.contact}><Snail avatar={a}/><View style={{flex:1,marginLeft:12}}><Text style={st.cardName}>{a.name}</Text><Text style={st.muted}>{a.phone||"Keine Nummer"}</Text></View><Pressable onPress={()=>setCall(a)} style={st.smallBtn}><Text>📞</Text></Pressable><Pressable onPress={()=>edit(a)} style={st.more}><Text>⋯</Text></Pressable></View>)}</ScrollView>}
  {tab==="create"&&<ScrollView contentContainerStyle={st.content}><Text style={st.pageTitle}>{editing?"Teleschnecke bearbeiten":"Teleschnecke erstellen"}</Text>
   <View style={st.preview}><Snail avatar={preview} large/><Text style={st.previewHint}>Live-Vorschau</Text></View>
   <Pressable style={st.secondary} onPress={choose}><Text style={st.secondaryText}>{photo?"📷 Foto ändern":"📷 Foto auswählen"}</Text></Pressable>
   <TextInput value={name} onChangeText={setName} placeholder="Name, z. B. Peter" placeholderTextColor={MUTED} style={st.input}/>
   <TextInput value={phone} onChangeText={setPhone} placeholder="Telefonnummer (optional)" placeholderTextColor={MUTED} keyboardType="phone-pad" style={st.input}/>
   <Text style={st.label}>Stil</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{(Object.keys(STYLE_LABELS) as AvatarStyle[]).map(x=><Pressable key={x} onPress={()=>setStyle(x)} style={[st.chip,style===x&&st.chipActive]}><Text style={st.chipText}>{STYLE_LABELS[x]}</Text></Pressable>)}</ScrollView>
   <Text style={st.label}>Ausdruck</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{(Object.keys(EXPRESSION_LABELS) as AvatarExpression[]).map(x=><Pressable key={x} onPress={()=>setExpression(x)} style={[st.chip,expression===x&&st.chipActive]}><Text style={st.chipText}>{EXPRESSION_LABELS[x]}</Text></Pressable>)}</ScrollView>
   <Text style={st.label}>Augen</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{(Object.keys(EYES_LABELS) as AvatarEyes[]).map(x=><Pressable key={x} onPress={()=>setEyes(x)} style={[st.chip,eyes===x&&st.chipActive]}><Text style={st.chipText}>{EYES_LABELS[x]}</Text></Pressable>)}</ScrollView>
   <Text style={st.label}>Zubehör</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{(Object.keys(ACCESSORY_LABELS) as AvatarAccessory[]).map(x=><Pressable key={x} onPress={()=>setAccessory(x)} style={[st.chip,accessory===x&&st.chipActive]}><Text style={st.chipText}>{ACCESSORY_LABELS[x]}</Text></Pressable>)}</ScrollView>
   <Text style={st.label}>Schneckenhaus</Text><View style={st.swatches}>{SHELLS.map(c=><Pressable key={c} onPress={()=>setShellColor(c)} style={[st.swatch,{backgroundColor:c},shellColor===c&&st.selected]}/>)}</View>
   <Text style={st.label}>Körper</Text><View style={st.swatches}>{BODIES.map(c=><Pressable key={c} onPress={()=>setBodyColor(c)} style={[st.swatch,{backgroundColor:c},bodyColor===c&&st.selected]}/>)}</View>
   <View style={st.privacyBox}><Text style={st.privacyTitle}>🔒 Foto bleibt lokal</Text><Text style={st.privacyText}>Version 1 lädt dein ausgewähltes Foto nicht auf einen Server hoch.</Text></View>
   <Pressable style={st.primary} onPress={save}><Text style={st.primaryText}>{editing?"Änderungen speichern":"Teleschnecke speichern"}</Text></Pressable>
   {editing&&<Pressable style={st.danger} onPress={()=>Alert.alert("Löschen","Teleschnecke wirklich löschen?",[{text:"Abbrechen"},{text:"Löschen",style:"destructive",onPress:()=>remove(editing)}])}><Text style={st.dangerText}>Teleschnecke löschen</Text></Pressable>}
  </ScrollView>}
  {tab==="settings"&&<ScrollView contentContainerStyle={st.content}><Text style={st.pageTitle}>Einstellungen</Text><View style={st.info}><Text style={st.infoTitle}>Datenschutz zuerst</Text><Text style={st.infoText}>In Version 1 bleiben Avatare und ausgewählte Fotos lokal auf dem Gerät. Es gibt keine Konten, Werbung oder Analyse-SDKs.</Text></View><View style={st.setting}><Text style={st.cardName}>Version</Text><Text style={st.muted}>1.0.0</Text></View><View style={st.setting}><Text style={st.cardName}>Anrufe</Text><Text style={st.muted}>werden über die native Telefon-App gestartet</Text></View></ScrollView>}
  <View style={st.nav}><Nav label="Start" icon="⌂" active={tab==="home"} onPress={()=>setTab("home")}/><Nav label="Kontakte" icon="🐌" active={tab==="contacts"} onPress={()=>setTab("contacts")}/><Nav label="Erstellen" icon="＋" active={tab==="create"} onPress={create}/><Nav label="Einstellungen" icon="⚙" active={tab==="settings"} onPress={()=>setTab("settings")}/></View>
 </SafeAreaView>;
}

const st=StyleSheet.create({
 safe:{flex:1,backgroundColor:BG},header:{padding:18,paddingTop:10,flexDirection:"row",justifyContent:"space-between",alignItems:"center",borderBottomWidth:1,borderBottomColor:"#1D2638"},logo:{color:TEXT,fontSize:19,fontWeight:"900",letterSpacing:2},tag:{color:MUTED,fontSize:11,marginTop:2},add:{width:42,height:42,borderRadius:14,backgroundColor:BLUE,alignItems:"center",justifyContent:"center"},addText:{color:BG,fontSize:27,fontWeight:"800"},
 content:{padding:18,paddingBottom:115},hero:{backgroundColor:PANEL,borderRadius:28,padding:22,borderWidth:1,borderColor:"#202C43",marginBottom:24},kicker:{color:BLUE,fontSize:10,fontWeight:"900",letterSpacing:1.5,marginBottom:10},title:{color:TEXT,fontSize:30,fontWeight:"900",lineHeight:35},copy:{color:MUTED,fontSize:14,lineHeight:21,marginTop:12},primary:{backgroundColor:BLUE,borderRadius:16,padding:15,alignItems:"center",marginTop:18},primaryText:{color:BG,fontWeight:"900"},section:{color:TEXT,fontSize:18,fontWeight:"900",marginBottom:12},card:{backgroundColor:PANEL,padding:12,borderRadius:20,width:132,marginRight:10,borderWidth:1,borderColor:"#202C43"},cardName:{color:TEXT,fontWeight:"800",fontSize:13},muted:{color:MUTED,fontSize:11,marginTop:3},info:{backgroundColor:"#0D1727",borderRadius:20,padding:16,borderWidth:1,borderColor:"#1C3554",marginTop:22},infoTitle:{color:TEXT,fontWeight:"900",fontSize:15},infoText:{color:MUTED,fontSize:12,lineHeight:18,marginTop:7},
 pageTitle:{color:TEXT,fontSize:28,fontWeight:"900",marginBottom:16},contact:{backgroundColor:PANEL,borderRadius:18,padding:10,marginBottom:10,flexDirection:"row",alignItems:"center",borderWidth:1,borderColor:"#202C43"},smallBtn:{width:42,height:42,borderRadius:14,backgroundColor:"#17392F",alignItems:"center",justifyContent:"center"},more:{width:34,alignItems:"center"},preview:{alignItems:"center",paddingVertical:12,backgroundColor:PANEL,borderRadius:24,marginBottom:14},previewHint:{color:MUTED,fontSize:10,marginTop:2},secondary:{backgroundColor:PANEL2,borderRadius:16,padding:14,alignItems:"center",borderWidth:1,borderColor:"#26334B",marginBottom:12},secondaryText:{color:TEXT,fontWeight:"800"},input:{backgroundColor:PANEL,borderRadius:15,borderWidth:1,borderColor:"#26334B",padding:14,color:TEXT,fontSize:15,marginBottom:10},label:{color:TEXT,fontWeight:"900",fontSize:13,marginTop:10,marginBottom:9},chip:{paddingHorizontal:15,paddingVertical:10,borderRadius:14,backgroundColor:PANEL,marginRight:8,borderWidth:1,borderColor:"#26334B"},chipActive:{borderColor:BLUE,backgroundColor:"#11253A"},chipText:{color:TEXT,fontWeight:"700"},swatches:{flexDirection:"row",gap:10,marginBottom:8},swatch:{width:40,height:40,borderRadius:20,borderWidth:2,borderColor:"#273148"},selected:{borderColor:TEXT,borderWidth:3},privacyBox:{marginTop:16,padding:13,borderRadius:16,backgroundColor:"#0D1727",borderWidth:1,borderColor:"#1C3554"},privacyTitle:{color:TEXT,fontWeight:"900",fontSize:12},privacyText:{color:MUTED,fontSize:11,lineHeight:16,marginTop:4},danger:{padding:15,alignItems:"center"},dangerText:{color:RED,fontWeight:"800"},setting:{backgroundColor:PANEL,padding:16,borderRadius:16,marginTop:10,borderWidth:1,borderColor:"#202C43"},
 nav:{position:"absolute",bottom:12,left:12,right:12,height:70,borderRadius:24,backgroundColor:"#0D1220",borderWidth:1,borderColor:"#202C43",flexDirection:"row",justifyContent:"space-around",alignItems:"center"},navItem:{alignItems:"center",justifyContent:"center",minWidth:70},navIcon:{fontSize:19,color:MUTED},navLabel:{fontSize:10,color:MUTED,marginTop:2},
 snail:{position:"relative",alignItems:"center"},shell:{position:"absolute",borderRadius:999,borderWidth:4,borderColor:"#C8D6F2",alignItems:"center",justifyContent:"center"},spiral:{color:"rgba(255,255,255,.55)"},shellMark:{position:"absolute",right:7,bottom:7,color:"#E8C27A"},shellGlow:{position:"absolute",width:"65%",height:"65%",borderRadius:999,borderWidth:2,borderColor:"#8DEBFF"},body:{position:"absolute",borderRadius:999,borderBottomLeftRadius:28,borderBottomRightRadius:28,alignItems:"center",justifyContent:"center",overflow:"hidden",borderWidth:2,borderColor:"rgba(0,0,0,.12)"},face:{borderRadius:999,borderWidth:2,borderColor:"#FFF",marginTop:-8},faceEmpty:{borderRadius:999,backgroundColor:"#F3D6B0",alignItems:"center",justifyContent:"center",marginTop:-8},mouth:{position:"absolute",bottom:14,borderBottomWidth:3,borderColor:"#5E2530"},ant:{position:"absolute",top:0,width:3,backgroundColor:"#D49D73",borderRadius:4},eye:{position:"absolute",top:-4,left:-6,borderWidth:2,borderColor:"#34211E"},glasses:{position:"absolute",top:19,flexDirection:"row",gap:2},glass:{width:21,height:15,borderRadius:8,borderWidth:2,borderColor:"#1A2333"},monocle:{position:"absolute",top:18,right:18,width:22,height:22,borderRadius:11,borderWidth:3,borderColor:"#D5B36A"},scarf:{position:"absolute",bottom:0,left:0,right:0,height:12,backgroundColor:"#B63A58"},hat:{position:"absolute",top:-3,alignItems:"center"},hatTop:{width:48,height:22,backgroundColor:"#232A38",borderTopLeftRadius:20,borderTopRightRadius:20},call:{flex:1,alignItems:"center",padding:22},back:{alignSelf:"flex-start",color:TEXT,fontSize:42},callTitle:{color:TEXT,fontSize:30,fontWeight:"900",marginBottom:5},callName:{color:TEXT,fontSize:24,fontWeight:"900",marginTop:8},callActions:{flexDirection:"row",gap:24,marginTop:28},callBtn:{width:105,height:105,borderRadius:53,alignItems:"center",justifyContent:"center"},callBtnText:{fontSize:34,color:"#FFF"},callBtnLabel:{fontSize:12,color:"#FFF",fontWeight:"900"},note:{color:MUTED,fontSize:11,textAlign:"center",lineHeight:17,marginTop:28,maxWidth:300}
});
