const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const state={name:localStorage.getItem("theoone_name")||"Nova",role:localStorage.getItem("theoone_role")||"Persönlicher Begleiter",personality:localStorage.getItem("theoone_personality")||"freundlich, direkt, kreativ und unterstützend",memory:JSON.parse(localStorage.getItem("theoone_memory")||"[]")};
const titles={home:"Dein Companion",chat:"Chat",memory:"Memory",skills:"Skills",companion:"Companion",settings:"Einstellungen"};
function save(){localStorage.setItem("theoone_name",state.name);localStorage.setItem("theoone_role",state.role);localStorage.setItem("theoone_personality",state.personality);localStorage.setItem("theoone_memory",JSON.stringify(state.memory))}
function refresh(){$("#companionName").textContent=state.name;$("#companionRole").textContent=state.role;$("#chatName").textContent=state.name;$("#memoryCount").textContent=state.memory.length;$("#nameInput").value=state.name;$("#roleInput").value=state.role;$("#personalityInput").value=state.personality;renderMemory()}
function show(view){$$(".view").forEach(v=>v.classList.remove("active"));$("#view-"+view).classList.add("active");$$(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===view));$("#pageTitle").textContent=titles[view]||"TheOone AI";window.scrollTo({top:0,behavior:"smooth"});$("#sidebar").classList.remove("open")}
$$(".nav-item").forEach(b=>b.addEventListener("click",()=>show(b.dataset.view)));$$("[data-go]").forEach(b=>b.addEventListener("click",()=>show(b.dataset.go)));$("#menuBtn").addEventListener("click",()=>$("#sidebar").classList.toggle("open"));
function addMessage(text,type){const d=document.createElement("div");d.className="bubble "+type;d.textContent=text;$("#messages").appendChild(d);$("#messages").scrollTop=$("#messages").scrollHeight}
function localReply(input){const t=input.toLowerCase();if(t.includes("tag")||t.includes("plan"))return"Gerne. Wir teilen den Tag in drei Schritte: 1) Wichtigstes Ziel festlegen, 2) Aufgaben bündeln, 3) einen konkreten nächsten Schritt starten.";if(t.includes("ziel"))return state.memory.some(x=>/ziel|möchte|will/i.test(x))?"Ich habe passende Ziele in deinem Memory gefunden. Öffne Memory, um sie zu sehen.":"Bisher habe ich noch kein konkretes Ziel gespeichert. Du kannst es unter Memory hinzufügen.";if(t.includes("hallo")||t.includes("hi"))return"Hallo! Ich bin "+state.name+". Ich bin bereit. Was möchtest du gemeinsam angehen?";return"Ich habe deine Nachricht verstanden. In dieser MVP-Version arbeite ich noch mit lokalen Demo-Antworten. Der nächste technische Schritt ist die Verbindung mit einem echten KI-Backend."}
$("#chatForm").addEventListener("submit",e=>{e.preventDefault();const input=$("#chatInput"),v=input.value.trim();if(!v)return;addMessage(v,"user");input.value="";setTimeout(()=>addMessage(localReply(v),"bot"),220)});
$$(".chat-side button").forEach(b=>b.addEventListener("click",()=>{show("chat");$("#chatInput").value=b.dataset.prompt;$("#chatInput").focus()}));
function renderMemory(){const list=$("#memoryList");list.innerHTML="";if(!state.memory.length){list.innerHTML='<div class="memory-item"><span>Noch nichts gespeichert. Dein Companion wartet auf den ersten Eintrag.</span></div>';return}state.memory.forEach((m,i)=>{const d=document.createElement("div");d.className="memory-item";const span=document.createElement("span");span.textContent=m;const btn=document.createElement("button");btn.className="delete";btn.textContent="Löschen";btn.onclick=()=>{state.memory.splice(i,1);save();refresh()};d.append(span,btn);list.appendChild(d)})}
$("#addMemory").onclick=()=>{const i=$("#memoryInput"),v=i.value.trim();if(!v)return;state.memory.unshift(v);i.value="";save();refresh()};
$("#saveCompanion").onclick=()=>{state.name=$("#nameInput").value.trim()||"Nova";state.role=$("#roleInput").value;state.personality=$("#personalityInput").value.trim();save();addMessage("Profil aktualisiert. Ich heiße jetzt "+state.name+" und bin dein "+state.role+".","bot");show("chat");refresh()};
$("#resetBtn").onclick=()=>{if(confirm("Alle lokalen TheOone-Daten löschen?")){["theoone_name","theoone_role","theoone_personality","theoone_memory"].forEach(k=>localStorage.removeItem(k));location.reload()}};
$("#memoryToggle").onchange=e=>{if(!e.target.checked)alert("Memory ist jetzt in der Oberfläche deaktiviert. Bereits gespeicherte lokale Daten bleiben erhalten, bis du sie unter Memory oder über Zurücksetzen entfernst.")};
addMessage("Hallo! Ich bin "+state.name+". Willkommen bei TheOone AI. Was möchtest du heute gemeinsam angehen?","bot");refresh();